// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmuNteq7X2ZghO0AI9Lwq42JZF6FpCZp4',
    appId: '1:222733444336:web:4573329e5b0bd8a8934e35',
    messagingSenderId: '222733444336',
    projectId: 'quickchat-d14fe',
    authDomain: 'quickchat-d14fe.firebaseapp.com',
    storageBucket: 'quickchat-d14fe.firebasestorage.app',
    measurementId: 'G-GT6JM87ZSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhOmtVPsCRFdHlooMODNI1agL08m13_IU',
    appId: '1:222733444336:android:b83da80d622f9589934e35',
    messagingSenderId: '222733444336',
    projectId: 'quickchat-d14fe',
    storageBucket: 'quickchat-d14fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV3OwD9PM_zARjRY4P6TjfTmiXhAYu17A',
    appId: '1:222733444336:ios:640aac3c91a97322934e35',
    messagingSenderId: '222733444336',
    projectId: 'quickchat-d14fe',
    storageBucket: 'quickchat-d14fe.firebasestorage.app',
    iosBundleId: 'com.example.chat2',
  );
}
